version: '3' 

services: 
    mariadb:
        image: mariadb:10.6
        ports:
            - "3306:3306"
        volumes:
        # 데이터 유지
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            # 초기 설정
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment:
            TZ: Asia/Seoul
            MARIADB_USER: marvin
            MARIA_DB_PASSWORD: test1234
            MARIADB_ROOT_PASSWORD: test1234
            MARIADB_DATABASE: marvin_project
        restart: always